### ISSUE TITLE
启动插件失败

### ISSUE THREAD

**Issue by fatinghenji** [nonebotjs/koishi-plugin-nonebot#12]
```java
2023-05-09 02:24:40 [I] nonebot warning: no blob constructor, cannot create blobs with mimetypes
2023-05-09 02:24:40 [I] nonebot warning: no BlobBuilder
2023-05-09 02:24:42 [I] nonebot Python initialization complete
2023-05-09 02:24:43 [I] nonebot Loading pil
2023-05-09 02:24:44 [I] nonebot Loaded pil
2023-05-09 02:24:44 [I] nonebot Loading numpy
2023-05-09 02:24:50 [W] market aborted
2023-05-09 02:24:50 [W] market aborted
2023-05-09 02:24:54 [I] nonebot Loaded numpy
2023-05-09 02:24:55 [W] app Error
                            at Object.ensureErrnoError (/home/koishi-app/node_modules/pyodide/pyodide.asm.js:10:328013)
                            at Object.staticInit (/home/koishi-app/node_modules/pyodide/pyodide.asm.js:10:328219)
                            at /home/koishi-app/node_modules/pyodide/pyodide.asm.js:10:865894
                            at loadPyodide (/home/koishi-app/node_modules/pyodide/pyodide.js:1:13502)
                            at async NoneBot.start (/home/koishi-app/node_modules/koishi-plugin-nonebot/lib/index.js:47:23)
                            at async /home/koishi-app/node_modules/cordis/lib/index.cjs:712:7
                            at async Promise.all (index 23)
                            at async Lifecycle.flush (/home/koishi-app/node_modules/cordis/lib/index.cjs:77:7)
                            at async Lifecycle.start (/home/koishi-app/node_modules/cordis/lib/index.cjs:164:5)
                            at async start (/home/koishi-app/node_modules/koishi/lib/worker/index.js:171:3)
```

**Comment by CyanChanges** [comment]
这是一个warning，实际上似乎不影响使用

**Comment by CyanChanges** [comment]
我这边 koishi.yml 中的 nonebot 配置不到为什么为 null, 改回 {} 就好了

**Comment by shigma** [comment]
> 我这边 koishi.yml 中的 nonebot 配置不到为什么为 null, 改回 {} 就好了

null 和 {} 是等价的。
